before:
  hooks:
    - go mod tidy
builds:
  - skip: true
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
sboms:
  - documents:
      - bom.json
    artifacts: any
    cmd: cyclonedx-gomod
    args: [ "mod", "-licenses", "-library", "-std", "-json", "-output", "$document", "." ]